---
name: customer-io
version: 0.1.0
synopsis: customer.io library
maintainer: Bitnomial <help@bitnomial.com>
homepage: https://customer.io
copyright: 2025 Bitnomial, Inc.
license: BSD-3-Clause

language: GHC2021

ghc-options:
    - -Wall
    - -Werror
    - -Wmissing-home-modules
    - -Widentities
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wpartial-fields
    - -Wmissing-export-lists
    - -Wno-unused-do-bind
    - -Wunused-packages
    - -funbox-strict-fields
    - -fwrite-ide-info

dependencies:
    - base
    - aeson
    - containers
    - http-client
    - http-client-tls
    - mtl
    - servant
    - servant-client
    - text

library:
    source-dirs: src/lib
    when:
        - condition: false
          other-modules: Paths_customer_io
